"""add patient profile photo path

Revision ID: 4264198d765d
Revises: e7a4c2d9f106
Create Date: 2026-09-19 16:45:32.114066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4264198d765d'
down_revision: Union[str, Sequence[str], None] = 'e7a4c2d9f106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elderly_patients', sa.Column('profile_photo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elderly_patients', 'profile_photo_path')
    # ### end Alembic commands ###
