"""add watch wear status

Revision ID: 8b27637d369b
Revises: e7a4c2d9f106
Create Date: 2026-09-21 17:29:05.922835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b27637d369b'
down_revision: Union[str, Sequence[str], None] = 'e7a4c2d9f106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_devices', sa.Column('is_worn', sa.Boolean(), nullable=True))
    op.add_column('monitoring_devices', sa.Column('not_worn_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_devices', 'not_worn_since')
    op.drop_column('monitoring_devices', 'is_worn')
    # ### end Alembic commands ###
